dist: trusty
sudo: false

language: node_js

node_js:
  - 4
  - 5
  - 6
  - 7
  - 8

env:
  - NODE_ENV=test WEBPACK_VERSION=1.x
  - NODE_ENV=test WEBPACK_VERSION=2.x
  - NODE_ENV=test WEBPACK_VERSION=3.x

before_install:
  - npm install -g npm
install:
  - npm install
script:
  - scripts/test.sh

matrix:
  allow_failures:
    - node_js: 8